AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  A simple backend (read/write to DynamoDB) with a RESTful API endpoint using
  Amazon API Gateway.
Resources:
  zipsearch:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: >-
        A simple backend (read/write to DynamoDB) with a RESTful API endpoint
        using Amazon API Gateway.
      MemorySize: 512
      Timeout: 30
      Role: 'arn:aws:iam::683161864268:role/lambda-zip-role'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /zip-search
            Method: GET
      Tags:
        'lambda-console:blueprint': microservice-http-endpoint-python
